(* test/unit/api/test_registry.ml
   Tests for lib/api/registry.ml — the function catalogue.

   The catalogue is generated by parsing the project's own .mli files, so these
   tests check two things that matter:

     1. The parser handles the declaration forms this codebase actually uses.
        Three files are traps: [tx_parser.mli] is a single [include module type of],
        and [field.mli] / [scalar.mli] expose everything through [module T]. A
        parser that only matched [^val] would report all three as empty, and the
        UI would show three blank libraries without anything appearing wrong.

     2. The catalogue is run against the REAL source tree, so it is checked against
        reality rather than a fixture that could drift from it. *)

(** The repository root, derived from this test's own location in _build. *)
let repo_root () =
  (* _build/default/test/unit/api/ -> up five levels *)
  let rec up dir n = if n = 0 then dir else up (Filename.dirname dir) (n - 1) in
  up (Sys.getcwd ()) 0 |> fun _ ->
  (* dune runs tests with cwd at the build dir for the stanza; walk up until
     dune-project appears, which is robust to layout changes. *)
  let rec find dir =
    if Sys.file_exists (Filename.concat dir "dune-project") then dir
    else
      let parent = Filename.dirname dir in
      if parent = dir then failwith "dune-project not found above " ^ Sys.getcwd ()
      else find parent
  in
  find (Sys.getcwd ())

let decls_of (ms : Registry.module_info list) (name : string) : Registry.decl list =
  match List.find_opt (fun m -> m.Registry.module_name = name) ms with
  | Some m -> m.Registry.decls
  | None -> []

(* The fixture helper below writes to a temp file, whose name is random, so the
   derived module name is random too.  Look declarations up by name and kind
   rather than by module. *)
let decl_named (m : Registry.module_info) (v : string) : Registry.decl option =
  List.find_opt (fun (d : Registry.decl) -> d.Registry.name = v) m.Registry.decls

let has_kind (m : Registry.module_info) (k : Registry.kind) : bool =
  List.exists (fun (d : Registry.decl) -> d.Registry.kind = k) m.Registry.decls

let has_val (ms : Registry.module_info list) (modname : string) (v : string) : bool =
  List.exists
    (fun (d : Registry.decl) -> d.Registry.kind = Registry.Val && d.Registry.name = v)
    (decls_of ms modname)

let names_of_kind (ms : Registry.module_info list) (modname : string) (k : Registry.kind) : string list =
  List.filter_map
    (fun (d : Registry.decl) -> if d.Registry.kind = k then Some d.Registry.name else None)
    (decls_of ms modname)

(* ------------------------------------------------------------------ unit-level *)

(* Hand-written fixtures for the parser's corner cases. parse_mli reads a file, so
   these go through a temporary file rather than being inlined. *)

let with_temp_mli contents f =
  let path = Filename.temp_file "regtest" ".mli" in
  let oc = open_out_bin path in
  output_string oc contents;
  close_out oc;
  (* parse_mli takes a root and a path relative to it; point the root at the
     temp file's directory and pass the basename. *)
  let dir = Filename.dirname path in
  let base = Filename.basename path in
  let result = f ~root:dir ~file:base in
  (try Sys.remove path with _ -> ());
  result

let test_parses_val () =
  let m =
    with_temp_mli "val foo : int -> int\n" (fun ~root ~file ->
        Registry.parse_mli ~root ~library:"test" ~file)
  in
  Alcotest.(check bool) "found val foo" true (decl_named m "foo" <> None)

let test_parses_doc_comment () =
  let m =
    with_temp_mli "(** Adds one to an integer. *)\nval incr_by_one : int -> int\n"
      (fun ~root ~file -> Registry.parse_mli ~root ~library:"test" ~file)
  in
  match decl_named m "incr_by_one" with
  | Some d ->
    (* Assert the two properties that matter to a consumer of /api/functions:
       the text is present, and no comment markup leaked into it.  Asserting an
       exact string here was brittle in a way that hid which half was wrong. *)
    (match d.Registry.doc with
     | None -> Alcotest.fail "doc was not captured at all"
     | Some doc ->
       Alcotest.(check bool) "contains the text" true
         (let re = Str.regexp_string "Adds one to an integer" in
          try ignore (Str.search_forward re doc 0); true with Not_found -> false);
       (* A leading [(**] or a trailing [*)] in the doc string would be rendered
          verbatim in the UI. Both must be absent. *)
       Alcotest.(check (option int)) "no opening marker" None
         (try Some (Str.search_forward (Str.regexp_string "(**") doc 0)
          with Not_found -> None);
       Alcotest.(check (option int)) "no closing marker" None
         (let n = String.length doc in
          if n >= 2 && String.sub doc (n - 2) 2 = "*)" then Some (n - 2) else None))
  | None -> Alcotest.fail "declaration not found"

let test_detached_doc_is_not_attached () =
  (* A blank line between a doc block and a declaration means the doc is not that
     declaration's. Attaching it anyway would put the wrong description in the UI. *)
  let m =
    with_temp_mli "(** Not about bar. *)\n\nval bar : int\n"
      (fun ~root ~file -> Registry.parse_mli ~root ~library:"test" ~file)
  in
  match List.find_opt (fun (d : Registry.decl) -> d.Registry.name = "bar") m.Registry.decls with
  | Some d -> Alcotest.(check (option string)) "doc not attached" None d.Registry.doc
  | None -> Alcotest.fail "declaration not found"

let test_parses_type () =
  let m =
    with_temp_mli "type t = A | B\n" (fun ~root ~file ->
        Registry.parse_mli ~root ~library:"test" ~file)
  in
  Alcotest.(check bool) "type captured" true (has_kind m Registry.Type_decl)

let test_parses_include () =
  (* An [include] must be recorded, not skipped: otherwise a module that is only an
     include reports zero declarations and looks empty. *)
  let m =
    with_temp_mli "include module type of Other\n" (fun ~root ~file ->
        Registry.parse_mli ~root ~library:"test" ~file)
  in
  Alcotest.(check bool) "include recorded" true (has_kind m Registry.Include)

let test_multiline_signature_collapsed () =
  let m =
    with_temp_mli "val f :\n  int ->\n  string ->\n  bool\n"
      (fun ~root ~file -> Registry.parse_mli ~root ~library:"test" ~file)
  in
  match List.find_opt (fun (d : Registry.decl) -> d.Registry.name = "f") m.Registry.decls with
  | Some d ->
    Alcotest.(check bool) "signature mentions all params" true
      (let s = d.Registry.signature in
       String.length s > 0
       && (try ignore (Str.search_forward (Str.regexp_string "string") s 0); true
           with Not_found -> false))
  | None -> Alcotest.fail "declaration not found"

(* ------------------------------------------------------------------ against the real tree *)

(* These run against the actual repository. If a module's interface changes shape
   in a way the catalogue can no longer describe, this fails. *)
let test_real_tree_parses () =
  let root = repo_root () in
  let ms = Registry.scan ~root in
  Alcotest.(check bool) "found more than 20 modules" true (List.length ms > 20);
  Alcotest.(check bool) "found more than 100 declarations" true
    (Registry.count_decls ms > 100)

let test_module_style_interfaces_are_not_empty () =
  (* The specific trap: field and scalar expose everything via [module T]. *)
  let root = repo_root () in
  let ms = Registry.scan ~root in
  List.iter
    (fun name ->
       let n = List.length (decls_of ms name) in
       Alcotest.(check bool) (Printf.sprintf "%s reports declarations" name) true (n > 0))
    ["Field"; "Scalar"; "Tx_parser"]

let test_include_only_module_not_empty () =
  let root = repo_root () in
  let ms = Registry.scan ~root in
  Alcotest.(check bool) "Tx_parser records its include" true
    (List.length (names_of_kind ms "Tx_parser" Registry.Include) > 0)

let test_known_declarations_present () =
  let root = repo_root () in
  let ms = Registry.scan ~root in
  (* Spot-check a few functions that definitely exist. *)
  Alcotest.(check bool) "Point.of_compressed" true (has_val ms "Point" "of_compressed");
  Alcotest.(check bool) "Der.of_bytes" true (has_val ms "Der" "of_bytes");
  Alcotest.(check bool) "Legacy.compute" true (has_val ms "Legacy" "compute");
  Alcotest.(check bool) "Bip143.compute" true (has_val ms "Bip143" "compute");
  Alcotest.(check bool) "Nonce.analyze_pair" true (has_val ms "Nonce" "analyze_pair");
  Alcotest.(check bool) "Statistics.compute_aggregate_stats" true
    (has_val ms "Statistics" "compute_aggregate_stats")

let test_every_module_has_a_file () =
  let root = repo_root () in
  let ms = Registry.scan ~root in
  List.iter
    (fun (m : Registry.module_info) ->
       Alcotest.(check bool)
         (Printf.sprintf "%s file exists" m.Registry.module_name)
         true
         (Sys.file_exists (Filename.concat root m.Registry.file)))
    ms

let test_json_is_well_formed () =
  let root = repo_root () in
  let ms = Registry.scan ~root in
  let json = Registry.to_json ms in
  let text = Json.to_string json in
  (* It must round-trip through the parser, which proves the catalogue is
     serialisable and not merely built. *)
  match Json.parse text with
  | Ok _ -> ()
  | Error e -> Alcotest.failf "catalogue JSON does not reparse: %s" e

let () =
  Alcotest.run "api-registry" [
    "parser", [
      "parses val",                `Quick, test_parses_val;
      "captures doc comment",      `Quick, test_parses_doc_comment;
      "detached doc not attached", `Quick, test_detached_doc_is_not_attached;
      "parses type",               `Quick, test_parses_type;
      "parses include",            `Quick, test_parses_include;
      "collapses multiline sig",   `Quick, test_multiline_signature_collapsed;
    ];
    "real tree", [
      "parses the repository",       `Quick, test_real_tree_parses;
      "module-style not empty",      `Quick, test_module_style_interfaces_are_not_empty;
      "include-only not empty",      `Quick, test_include_only_module_not_empty;
      "known declarations present",  `Quick, test_known_declarations_present;
      "every module file exists",    `Quick, test_every_module_has_a_file;
      "json reparseable",            `Quick, test_json_is_well_formed;
    ];
  ]
