(tests
 (names test_tx_types test_tx_parser)
 (libraries bitcoin_tx alcotest))

(tests
 (names prop_tx_parser)
 (libraries bitcoin_tx qcheck qcheck-alcotest alcotest))

(tests
 (names test_script_types test_script_parser)
 (libraries script_types alcotest))

(tests
 (names test_signature_extraction)
 (flags
  (:standard -w -32-33))
 (libraries bitcoin alcotest))
