(executables
 (names test_tx_types test_tx_parser)
 (libraries bitcoin_tx alcotest))

(executable
 (name prop_tx_parser)
 (libraries bitcoin_tx qcheck qcheck-alcotest alcotest))

(executables
 (names test_script_types test_script_parser)
 (libraries script_types alcotest))

(executable
 (name test_signature_extraction)
 (libraries bitcoin alcotest))

